export type Language = 'en' | 'zh';

export interface Translations {
  // App
  appName: string;
  capture: string;
  create: string;
  generate: string;
  caption: string;
  apiKeyConfigured: string;
  setApiKey: string;
  geminiVeo: string;
  allRightsReserved: string;
  legalPolicies: string;

  // Video Player
  uploadVideo: string;
  dragDropOrClick: string;
  selectLocalVideo: string;
  or: string;
  enterMp4Url: string;
  load: string;
  example: string;
  removeVideo: string;
  back5Frames: string;
  previousFrame: string;
  pause: string;
  play: string;
  nextFrame: string;
  forward5Frames: string;
  captureFrame: string;
  fileTooLarge: string;
  maxSize: string;

  // Gallery
  gallery: string;
  noCaptures: string;
  captureTip: string;
  downloadImage: string;
  deleteImage: string;

  // Sidebar
  noSelection: string;
  clickGalleryToView: string;
  materialDetails: string;
  id: string;
  timestamp: string;
  resolution: string;
  size: string;
  createdAt: string;
  aiGeneratedContent: string;
  aiGeneratedDesc: string;
  download: string;
  delete: string;

  // Creative Studio
  creativeStudio: string;
  selectFrameToStart: string;
  sourceImage: string;
  analyze: string;
  analyzing: string;
  smartAnalyze: string;
  chineseDesc: string;
  englishPrompt: string;
  copyContent: string;
  aspectRatio: string;
  quantity: string;
  startGenerating: string;
  generating: string;
  generatedImagesAppear: string;
  saveToGallery: string;
  downloadOriginal: string;
  
  // Veo Studio
  selectAtLeastOneFrame: string;
  startFrame: string;
  endFrameOptional: string;
  prompt: string;
  promptHint: string;
  aspectRatioVeo: string;
  generateVideo: string;
  generatingVideo: string;
  videoTip: string;
  thirdPartyTools: string;
  preview: string;
  selectStartAndEndFrames: string;
  
  // Modals
  contentRightsTitle: string;
  contentRightsDesc: string;
  aiGenRightsTitle: string;
  aiGenRightsDesc: string;
  videoGenRightsTitle: string;
  videoGenRightsDesc: string;
  confirm: string;
  cancel: string;
  iConfirm: string;
  whyRequired: string;
  hideDetails: string;
  legalCompliance: string;
  legalNote: string;
}

const en: Translations = {
  // App
  appName: 'ClipForge AI',
  capture: 'Capture',
  create: 'Create',
  generate: 'Generate',
  caption: 'Caption',
  apiKeyConfigured: 'API Key Configured',
  setApiKey: 'Set API Key',
  geminiVeo: 'Gemini 3 + Veo',
  allRightsReserved: 'All Rights Reserved.',
  legalPolicies: 'Legal & Policies',

  // Video Player
  uploadVideo: 'Upload Video',
  dragDropOrClick: 'Drag & drop file here, or click below to browse',
  selectLocalVideo: 'Select Local Video',
  or: 'OR',
  enterMp4Url: 'Enter MP4 URL...',
  load: 'Load',
  example: 'Example:',
  removeVideo: 'Remove video',
  back5Frames: 'Back 5 frames',
  previousFrame: 'Previous frame (←)',
  pause: 'Pause (Space)',
  play: 'Play (Space)',
  nextFrame: 'Next frame (→)',
  forward5Frames: 'Forward 5 frames',
  captureFrame: 'Capture current frame',
  fileTooLarge: 'File too large',
  maxSize: 'Max 500MB',

  // Gallery
  gallery: 'Gallery (Captures & Generated)',
  noCaptures: 'No captures yet',
  captureTip: 'Click Capture while playing video',
  downloadImage: 'Download image',
  deleteImage: 'Delete image',

  // Sidebar
  noSelection: 'No selection',
  clickGalleryToView: 'Click image in gallery to view details',
  materialDetails: 'Material Details',
  id: 'ID',
  timestamp: 'Timestamp',
  resolution: 'Resolution',
  size: 'Size',
  createdAt: 'Created',
  aiGeneratedContent: 'AI Generated Content',
  aiGeneratedDesc: 'This image was generated by Gemini model, not a video capture.',
  download: 'Download',
  delete: 'Delete',

  // Creative Studio
  creativeStudio: 'Creative Studio',
  selectFrameToStart: 'Select a frame from the left to start AI analysis and creation.',
  sourceImage: 'Source Image',
  analyze: 'Analyze',
  analyzing: 'Analyzing...',
  smartAnalyze: 'Smart Analyze',
  chineseDesc: 'Chinese Scene Description',
  englishPrompt: 'English Prompt (for generation)',
  copyContent: 'Copy content',
  aspectRatio: 'Aspect Ratio',
  quantity: 'Quantity',
  startGenerating: 'Start Generating',
  generating: 'Generating...',
  generatedImagesAppear: 'Generated images will appear here',
  saveToGallery: 'Save to Gallery',
  downloadOriginal: 'Download Original',
  
  // Veo Studio
  selectAtLeastOneFrame: 'Please select at least one start frame.',
  startFrame: 'Start Frame',
  endFrameOptional: 'End Frame (Optional)',
  prompt: 'Prompt',
  promptHint: 'Describe the action, e.g., light change, clouds moving...',
  aspectRatioVeo: 'Aspect Ratio',
  generateVideo: 'Generate Video (Veo)',
  generatingVideo: 'Generating (1-2 min)...',
  videoTip: 'Veo requires a paid API Key. Set your key in the top right.',
  thirdPartyTools: 'Third-party image-to-video tools:',
  preview: 'Preview',
  selectStartAndEndFrames: 'Select start and optional end frames to generate video',
  
  // Modals
  contentRightsTitle: 'Content Rights Confirmation',
  contentRightsDesc: 'Before capturing frames from this video, please confirm you have the rights to use this content.',
  aiGenRightsTitle: 'AI Generation Rights Confirmation',
  aiGenRightsDesc: 'Before generating new content with AI, please confirm you have the rights to the source material.',
  videoGenRightsTitle: 'Video Generation Rights Confirmation',
  videoGenRightsDesc: 'Before generating a video, please confirm you have rights to the source images and prompts.',
  confirm: 'Confirm',
  cancel: 'Cancel',
  iConfirm: 'I confirm I own or have the rights to use this content, including any music, images, or other media within it.',
  whyRequired: 'Why is this required?',
  hideDetails: 'Hide details',
  legalCompliance: 'Legal & Compliance:',
  legalNote: 'This helps us maintain compliance with copyright laws and platform policies. Your confirmation creates a record of your acknowledgment.',
};

const zh: Translations = {
  // App
  appName: 'ClipForge AI',
  capture: '采集',
  create: '创作',
  generate: '生成',
  caption: '文案',
  apiKeyConfigured: 'API Key 已配置',
  setApiKey: '设置 API Key',
  geminiVeo: 'Gemini 3 + Veo',
  allRightsReserved: '版权所有',
  legalPolicies: '法律与政策',

  // Video Player
  uploadVideo: '上传视频',
  dragDropOrClick: '拖拽文件到此处，或点击下方按钮选择',
  selectLocalVideo: '选择本地视频文件',
  or: 'OR',
  enterMp4Url: '输入MP4网络地址...',
  load: '加载',
  example: '示例:',
  removeVideo: '移除视频',
  back5Frames: '后退5帧',
  previousFrame: '上一帧 (←)',
  pause: '暂停 (Space)',
  play: '播放 (Space)',
  nextFrame: '下一帧 (→)',
  forward5Frames: '前进5帧',
  captureFrame: '捕获当前帧画面',
  fileTooLarge: '文件过大',
  maxSize: '最大 500MB',

  // Gallery
  gallery: '素材库 (截图 & 生成)',
  noCaptures: '暂无截图',
  captureTip: '播放视频时点击"截取画面"按钮',
  downloadImage: '下载图片',
  deleteImage: '删除图片',

  // Sidebar
  noSelection: '暂无选中素材',
  clickGalleryToView: '请在底部的素材库中点击图片查看详细信息',
  materialDetails: '素材详情',
  id: 'ID',
  timestamp: '时间戳',
  resolution: '分辨率',
  size: '大小',
  createdAt: '创建时间',
  aiGeneratedContent: 'AI 生成内容',
  aiGeneratedDesc: '该图像由 Gemini 模型生成，并非原始视频截图。',
  download: '下载',
  delete: '删除',

  // Creative Studio
  creativeStudio: '创意工坊',
  selectFrameToStart: '请先在左侧选择一张截图，开始进行 AI 分析与创作。',
  sourceImage: '原始画面',
  analyze: '分析',
  analyzing: '分析中...',
  smartAnalyze: '智能分析',
  chineseDesc: '中文场景描述',
  englishPrompt: '英文生图提示词 (Prompt)',
  copyContent: '复制内容',
  aspectRatio: '画幅比例',
  quantity: '数量',
  startGenerating: '开始生成',
  generating: '创作中...',
  generatedImagesAppear: '生成的图片将显示在这里',
  saveToGallery: '收藏到库',
  downloadOriginal: '下载原图',
  
  // Veo Studio
  selectAtLeastOneFrame: '请至少选择一个起始帧。',
  startFrame: '起始帧',
  endFrameOptional: '结束帧 (可选)',
  prompt: '提示词',
  promptHint: '描述视频中的动作，例如：光影变化，云雾缭绕...',
  aspectRatioVeo: '画幅',
  generateVideo: '生成视频 (Veo)',
  generatingVideo: '生成中 (需1-2分钟)...',
  videoTip: 'Veo 模型需要付费 API Key。请在右上角 "Set API Key" 设置您的 Key。',
  thirdPartyTools: '第三方图生视频工具推荐：',
  preview: '预览区域',
  selectStartAndEndFrames: '选择 起始帧 和 可选的 结束帧 来生成视频',
  
  // Modals
  contentRightsTitle: '内容版权确认',
  contentRightsDesc: '在捕获视频帧之前，请确认您有权使用此内容。',
  aiGenRightsTitle: 'AI 生成版权确认',
  aiGenRightsDesc: '在使用 AI 生成新内容之前，请确认您对源素材拥有权限。',
  videoGenRightsTitle: '视频生成版权确认',
  videoGenRightsDesc: '在生成视频之前，请确认您对源图片和提示词拥有权限。',
  confirm: '确认',
  cancel: '取消',
  iConfirm: '我确认我拥有或有权使用此内容，包括其中的任何音乐、图像或其他媒体。',
  whyRequired: '为什么需要这个？',
  hideDetails: '隐藏详情',
  legalCompliance: '法律合规：',
  legalNote: '这有助于我们保持对版权法和平台政策的合规性。您的确认创建了您知情的记录。',
};

export const translations: Record<Language, Translations> = { en, zh };

export function t(key: keyof Translations, lang: Language): string {
  return translations[lang][key];
}